@4000000041dd7c6939809e84 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
@4000000041dd7c693980d14c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] server->client: aes128-cbc hmac-md5 none
@4000000041dd7c693980f474 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] client->server: aes128-cbc hmac-md5 none
@4000000041dd7c6a0141b184 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] starting service ssh-userauth
@4000000041dd7c6a01688ad4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] eric trying auth none
@4000000041dd7c6a01ad504c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] eric trying auth publickey
@4000000041dd7c6a02cc8b8c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] eric failed auth publickey
@4000000041dd7c6a02d2ffe4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] reason:
@4000000041dd7c6a02da81c4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] Traceback (most recent call last):
@4000000041dd7c6a02e2654c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dd7c6a02f5e57c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a02fd8a84 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dd7c6a03102054 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a0317b1d4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dd7c6a032a247c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a0333c16c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dd7c6a0346b8e4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a034d5064 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] --- <exception caught here> ---
@4000000041dd7c6a035493c4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dd7c6a0366cbd4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a036df3dc 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dd7c6a038089ac 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a03882eb4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dd7c6a039aa92c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a03a2cb34 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dd7c6a03a8f16c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] None
@4000000041dd7c6a03f0915c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] eric trying auth publickey
@4000000041dd7c6a057a0fbc 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] eric failed auth publickey
@4000000041dd7c6a0580802c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] reason:
@4000000041dd7c6a05879894 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] Traceback (most recent call last):
@4000000041dd7c6a058fa32c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dd7c6a05a34a6c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a05aaef74 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dd7c6a05bd6604 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a05c47a84 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dd7c6a05d752bc 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a05de24d4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dd7c6a05eff754 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a05f7272c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] --- <exception caught here> ---
@4000000041dd7c6a05fe531c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dd7c6a0610dd34 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a06188624 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dd7c6a062b180c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a0632a5a4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dd7c6a06451464 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98]     
@4000000041dd7c6a064ca5e4 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dd7c6a06533d64 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] None
@4000000041dd7c6a3ada372c 2005/01/06 11:58 CST [SSHServerTransport,10,192.168.1.98] connection lost
@4000000041dda468159b6cec 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
@4000000041dda46815a25674 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] server->client: aes128-cbc hmac-md5 none
@4000000041dda46815a8d29c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] client->server: aes128-cbc hmac-md5 none
@4000000041dda4681ab0f83c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] starting service ssh-userauth
@4000000041dda4681ad8371c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] root trying auth none
@4000000041dda4681b70dd3c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] root trying auth publickey
@4000000041dda4681c65dbfc 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] root failed auth publickey
@4000000041dda4681c6c5ff4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] reason:
@4000000041dda4681c73e5bc 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] Traceback (most recent call last):
@4000000041dda4681cb13cdc 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dda4681cb1832c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681cb19a9c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dda4681cb1c594 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681cb2a43c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dda4681cbcd1b4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681cc48274 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dda4681cd6c63c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681cdd3a94 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] --- <exception caught here> ---
@4000000041dda4681ce51264 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dda4681cf7f654 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681cffaee4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dda4681d12600c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681d198814 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dda4681d2c875c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681d345374 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dda4681d3aeaf4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] None
@4000000041dda4681db2bad4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] root trying auth publickey
@4000000041dda4681f3c44ec 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] root failed auth publickey
@4000000041dda4681f433644 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] reason:
@4000000041dda4681f4a79a4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] Traceback (most recent call last):
@4000000041dda4681f5297c4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dda4681f68080c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681f6f8dd4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dda4681f825a54 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681f899db4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dda4681f9ca0e4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681fe91b04 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dda4681fe9559c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681fe970f4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] --- <exception caught here> ---
@4000000041dda4681fe98c4c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dda4681fea7a94 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681fea95ec 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dda4681feac0e4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda4681fede97c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dda4682001cb54 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98]     
@4000000041dda468200a4f04 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dda468201088c4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] None
@4000000041dda46b272e3c3c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] root trying auth password
@4000000041dda46b272e6b1c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] root failed auth password
@4000000041dda46b272e8a5c 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] reason:
@4000000041dda46b272ea5b4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] Failure: twisted.cred.error.UnauthorizedLogin: 
@4000000041dda46b272ec4f4 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] None
@4000000041dda46c20601bdc 2005/01/06 14:49 CST [SSHServerTransport,11,192.168.1.98] connection lost
@4000000041dda46f146a4f8c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
@4000000041dda46f146a8254 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] server->client: aes128-cbc hmac-md5 none
@4000000041dda46f146aa57c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] client->server: aes128-cbc hmac-md5 none
@4000000041dda46f1771b774 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] starting service ssh-userauth
@4000000041dda46f17acb504 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] eric trying auth none
@4000000041dda46f17ebaa34 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] eric trying auth publickey
@4000000041dda46f191d09fc 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] eric failed auth publickey
@4000000041dda46f191d3cc4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] reason:
@4000000041dda46f191d5434 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] Traceback (most recent call last):
@4000000041dda46f191d7374 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dda46f1920de74 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1927a0ec 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dda46f193d0964 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1944681c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dda46f19572ccc 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f195ee55c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dda46f1971b5c4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1978f154 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] --- <exception caught here> ---
@4000000041dda46f1980500c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dda46f199293d4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f199a34f4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dda46f19ace61c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f19b4120c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dda46f19c74fd4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f19cf0c4c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dda46f19d59fe4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] None
@4000000041dda46f1a1e2a34 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] eric trying auth publickey
@4000000041dda46f1baaf454 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] eric failed auth publickey
@4000000041dda46f1bb20cbc 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] reason:
@4000000041dda46f1bb93c94 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] Traceback (most recent call last):
@4000000041dda46f1bc156cc 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dda46f1bd55014 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1bdd145c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dda46f1befb5e4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1bf6ed8c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dda46f1c0a082c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1c11341c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dda46f1c234cec 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1c2a887c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] --- <exception caught here> ---
@4000000041dda46f1c31eb1c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dda46f1c4501d4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1c4c702c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dda46f1c5f253c 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1c699904 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dda46f1c7c88ac 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98]     
@4000000041dda46f1c84d1c4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dda46f1c8b03b4 2005/01/06 14:49 CST [SSHServerTransport,12,192.168.1.98] None
@4000000041dda49629be9794 2005/01/06 14:50 CST [SSHServerTransport,12,192.168.1.98] connection lost
@4000000041dda4971d213cbc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
@4000000041dda4971d21736c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] server->client: aes128-cbc hmac-md5 none
@4000000041dda4971d2192ac 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] client->server: aes128-cbc hmac-md5 none
@4000000041dda49720ffd67c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] starting service ssh-userauth
@4000000041dda497212709a4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] eric trying auth none
@4000000041dda497216cffcc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] eric trying auth publickey
@4000000041dda497228ecb4c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] eric failed auth publickey
@4000000041dda4972295ad04 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] reason:
@4000000041dda497229cfc1c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] Traceback (most recent call last):
@4000000041dda49722a550ec 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dda49722b9464c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49722c056e4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dda49722d2fc54 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49722da439c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dda49722ed0c34 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49722f4e01c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dda4972307b084 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda497230ef7cc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] --- <exception caught here> ---
@4000000041dda497235bc00c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dda497235bfe8c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda497235c15fc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dda497235c40f4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda497235d2b54 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dda497235d564c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda497235d6dbc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dda497235fbb94 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] None
@4000000041dda49723a68c7c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] eric trying auth publickey
@4000000041dda49725324cfc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] eric failed auth publickey
@4000000041dda4972539617c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] reason:
@4000000041dda4972540859c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] Traceback (most recent call last):
@4000000041dda4972548c2fc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 98, in ssh_USERAUTH_REQUEST
@4000000041dda497255c1064 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49725637ad4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 84, in tryAuth
@4000000041dda4972576148c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda497257d57ec 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/ssh/userauth.py", line 144, in auth_publickey
@4000000041dda49725905734 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda4972597bdbc 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/cred/portal.py", line 94, in login
@4000000041dda49725aa47d4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49725b1c1e4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] --- <exception caught here> ---
@4000000041dda49725b91cb4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 104, in maybeDeferred
@4000000041dda49725cbc60c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49725ecbb8c 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 78, in requestAvatarId
@4000000041dda49725ecfdf4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49725ed1564 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]   File "/dev/shm/usr/lib/python2.4/site-packages/twisted/conch/checkers.py", line 98, in checkKey
@4000000041dda49725fe6ae4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98]     
@4000000041dda49726062b44 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] exceptions.OSError: [Errno 1] Operation not permitted
@4000000041dda497260cda34 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] None
@4000000041dda499160a95f4 2005/01/06 14:50 CST [SSHServerTransport,13,192.168.1.98] connection lost
