Index: twisted/test/test_defer.py
===================================================================
--- twisted/test/test_defer.py	(revision 22074)
+++ twisted/test/test_defer.py	(working copy)
@@ -566,7 +566,6 @@
         d.addBoth(lambda ign: None)
 
 
-
 class LogTestCase(unittest.TestCase):
     """
     Test logging of unhandled errors.
@@ -630,7 +629,19 @@
         gc.collect()
         self._check()
 
+    def test_errorLogWithFailureCycle(self):
+        """
+        Same as L{test_errorLog}, but the deferred holds a failure
+        that refers back to itself.
+        """
+        d = defer.Deferred()
+        f = failure.Failure(Exception(d))
+        d.errback(f)
+        del d, f
+        gc.collect()
+        self._check()
 
+
 class DeferredTestCaseII(unittest.TestCase):
     def setUp(self):
         self.callbackRan = 0
