
===============================================================================
[SKIPPED]: twisted.vfs.test.test_sftp.SFTPAdapterTest.test_setAttrsFile

The VFS backend <twisted.vfs.backends.inmem.FakeDirectory instance at 0x47c9990c> doesn't support setAttrs
===============================================================================
[SKIPPED]: twisted.vfs.test.test_sftp.SFTPAdapterTest.test_setAttrsPath

The VFS backend <twisted.vfs.backends.inmem.FakeDirectory instance at 0x47ab8e2c> doesn't support setAttrs
===============================================================================
[SKIPPED]: twisted.web2.dav.test.test_prop.PROP.test_PROPPATCH_basic

No dead property store available for DAVFile.  Install xattr (http://undefined.org/python/#xattr) to enable use of dead properties.
===============================================================================
[SKIPPED]: twisted.web2.dav.test.test_report_expand.REPORT_expand.test_REPORT_expand_property

test unimplemeted
===============================================================================
[SKIPPED]: twisted.web2.test.test_http.SSLServerTest.testBasicWorkingness

Required SSL support missing from reactor
===============================================================================
[SKIPPED]: twisted.web2.test.test_http.SSLServerTest.testLingeringClose

Required SSL support missing from reactor
===============================================================================
[SKIPPED]: twisted.pb.test.test_banana.ThereAndBackAgain.test_boundMethod_newstyle

new-style classes still broken
===============================================================================
[SKIPPED]: twisted.pb.test.test_banana.ThereAndBackAgain.test_classMethod_newstyle

new-style classes still broken
===============================================================================
[SKIPPED]: twisted.pb.test.test_banana.ThereAndBackAgain.test_class_newstyle

new-style classes still broken
===============================================================================
[SKIPPED]: twisted.pb.test.test_banana.ThereAndBackAgain.test_instance_newstyle

new-style classes still broken
===============================================================================
[SKIPPED]: twisted.pb.test.test_crypto.TestListeners.testClone

crypto not available, shared ports require TubIDs and thus crypto
===============================================================================
[SKIPPED]: twisted.pb.test.test_crypto.TestListeners.testGetPort2

crypto not available, shared ports require TubIDs and thus crypto
===============================================================================
[SKIPPED]: twisted.pb.test.test_crypto.TestListeners.testShared

crypto not available, shared ports require TubIDs and thus crypto
===============================================================================
[SKIPPED]: twisted.pb.test.test_crypto.TestListeners.testSharedTransfer

crypto not available, shared ports require TubIDs and thus crypto
===============================================================================
[SKIPPED]: twisted.pb.test.test_crypto.TestPersist.testPersist

crypto not available
===============================================================================
[SKIPPED]: twisted.names.test.test_names.HostsTestCase.testIPv6

IPv6 support is not in our hosts resolver yet
===============================================================================
[SKIPPED]: twisted.web.test.test_http.QueryArgumentsTestCase.testEscchar

_c_urlarg module is not available
===============================================================================
[SKIPPED]: twisted.web.test.test_http.QueryArgumentsTestCase.testUnquote

_c_urlarg module is not available
===============================================================================
[SKIPPED]: twisted.web.test.test_soap.SOAPTestCase.testResults

SOAPpy not installed
===============================================================================
[SKIPPED]: twisted.web.test.test_web.GoogleTestCase.testCheckGoogle

no violation of google ToS
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientRedirectBetweenSSLandPlainText.testHoppingAround

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientRedirectBetweenSSLandPlainText.testHoppingAround

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testBrokenDownload

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testDownloadPage

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testDownloadPageError1

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testDownloadPageError2

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testDownloadPageError3

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testDownloadServerError

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testFactoryInfo

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testGetPage

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testHostHeader

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testPartial

Cannot test until webserver can serve partial data properly
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testPayload

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testRedirect

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testServerError

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testTimeoutNotTriggering

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientSSLTestCase.testTimeoutTriggering

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.web.test.test_webclient.WebClientTestCase.testPartial

Cannot test until webserver can serve partial data properly
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.FirebirdADBAPITestCase.testPool

Firebird: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.FirebirdReconnectTestCase.testPool

Firebird: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.GadflyADBAPITestCase.testPool

Gadfly: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.GadflyReconnectTestCase.testPool

Gadfly: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.MySQLADBAPITestCase.testPool

MySQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.MySQLReconnectTestCase.testPool

MySQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PsycopgADBAPITestCase.testPool

Psycopg: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PsycopgReconnectTestCase.testPool

Psycopg: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PyPgSQLADBAPITestCase.testPool

PyPgSQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PyPgSQLReconnectTestCase.testPool

PyPgSQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.SQLiteADBAPITestCase.testPool

SQLite: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.SQLiteReconnectTestCase.testPool

SQLite: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_doc.DocCoverage.testModules

Activate me when you feel like writing docstrings, and fixing GTK crashing bugs.
===============================================================================
[SKIPPED]: twisted.test.test_internet.InterfaceTestCase.testCallLaterOrder

Trial bug, todo doesn't work! See bug 1397
===============================================================================
[SKIPPED]: twisted.test.test_internet.InterfaceTestCase.testCallLaterOrder2

Trial bug, todo doesn't work! See bug 1397
===============================================================================
[SKIPPED]: twisted.test.test_newcred.PluggableAuthenticationModulesTest.testBadCredentials

Can't run without PyPAM
===============================================================================
[SKIPPED]: twisted.test.test_newcred.PluggableAuthenticationModulesTest.testBadUsername

Can't run without PyPAM
===============================================================================
[SKIPPED]: twisted.test.test_newcred.PluggableAuthenticationModulesTest.testRequestAvatarId

Can't run without PyPAM
===============================================================================
[SKIPPED]: twisted.test.test_paths.FilePathTestCase.testInsecureWin32

Consider yourself lucky.
===============================================================================
[SKIPPED]: twisted.test.test_paths.FilePathTestCase.testInsecureWin32Whacky

Consider yourself lucky.
===============================================================================
[SKIPPED]: twisted.test.test_policies.ThrottlingTestCase.testReadLimit

Inaccurate tests are worse than no tests.
===============================================================================
[SKIPPED]: twisted.test.test_policies.ThrottlingTestCase.testWriteLimit

Inaccurate tests are worse than no tests.
===============================================================================
[SKIPPED]: twisted.test.test_process.TestTwoProcessesNonPosix.testClose

wrong platform or reactor doesn't support IReactorProcess
===============================================================================
[SKIPPED]: twisted.test.test_process.Win32ProcessTestCase.testBadArgs

wrong platform or reactor doesn't support IReactorProcess
===============================================================================
[SKIPPED]: twisted.test.test_process.Win32ProcessTestCase.testStdinReader

wrong platform or reactor doesn't support IReactorProcess
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.FirebirdReflectorTestCase.testReflector

Firebird: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.FirebirdReflectorTestCase.testSaveAndDelete

Firebird: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.GadflyReflectorTestCase.testReflector

Gadfly: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.GadflyReflectorTestCase.testSaveAndDelete

Gadfly: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.MySQLReflectorTestCase.testReflector

MySQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.MySQLReflectorTestCase.testSaveAndDelete

MySQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PsycopgReflectorTestCase.testReflector

Psycopg: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PsycopgReflectorTestCase.testSaveAndDelete

Psycopg: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PyPgSQLReflectorTestCase.testReflector

PyPgSQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.PyPgSQLReflectorTestCase.testSaveAndDelete

PyPgSQL: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.SQLiteReflectorTestCase.testReflector

SQLite: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_adbapi.SQLiteReflectorTestCase.testSaveAndDelete

SQLite: Cannot access db
===============================================================================
[SKIPPED]: twisted.test.test_ssl.BufferingTestCase.testOpenSSLBuffering

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.ConnectionLostTestCase.testFailedVerify

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.ConnectionLostTestCase.testImmediateDisconnect

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.ConnectionLostTestCase.testFailedVerify

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.ConnectionLostTestCase.testImmediateDisconnect

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.SpammyTLSTestCase.testBackwardsTLS

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.SpammyTLSTestCase.testTLS

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.SpammyTLSTestCase.testUnTLS

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.StolenTCPTestCase.testProperlyCloseFiles

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.StolenTCPTestCase.testWriter

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.TLSTestCase.testBackwardsTLS

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.TLSTestCase.testTLS

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_ssl.TLSTestCase.testUnTLS

Reactor does not support SSL, cannot run SSL tests
===============================================================================
[SKIPPED]: twisted.test.test_udp.MulticastTestCase.testMultiListen

on non-linux platforms it appears multiple processes can listen, but not multiple sockets in same process?
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testAPileOfThings

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testFailedStartTLS

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testLoginLogin

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testStartTLS

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testAPileOfThings

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testFailedStartTLS

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testLoginLogin

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_imap.TLSTestCase.testStartTLS

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_pop3client.POP3TLSTestCase.testStartTLS

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_pop3client.POP3TLSTestCase.testStartTLS

OpenSSL not present
===============================================================================
[SKIPPED]: twisted.mail.test.test_smtp.TLSTestCase.testTLS

Reactor doesn't support SSL
===============================================================================
[SKIPPED]: twisted.mail.test.test_smtp.TLSTestCase.testTLS

Reactor doesn't support SSL
===============================================================================
[TODO]: twisted.conch.test.test_text.EfficiencyTestCase.testComplexStructure

Reason: "flatten() isn't quite stateful enough to avoid emitting a few extra bytes in certain circumstances, so these tests fail.  The failures take the form of additional elements in the ;-delimited character attribute lists.  For example, \\x1b[0;31;46m might be emitted instead of \\x[46m, even if 31 has already been activated and no conflicting attributes are set which need to be cleared."
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_text.py", line 87, in testComplexStructure
    "\x1b[1;31;46mForeground Red, Background Cyan, Bold"
<class 'twisted.trial.unittest.FailTest'>: '\x1b[1;31;46mForeground Red, Background Cyan, Bold\x1b[1;5;31;46mBlinking\x1b[0;31;46mForeground Red, Background Cyan, normal\x1b[1;32;46mForeground Green, Background Cyan, Bold' != '\x1b[1;31;46mForeground Red, Background Cyan, Bold\x1b[5mBlinking\x1b[0;31;46mForeground Red, Background Cyan, normal\x1b[1;32;46mForeground Green, Background Cyan, Bold'
===============================================================================
[TODO]: twisted.conch.test.test_text.EfficiencyTestCase.testNesting

Reason: "flatten() isn't quite stateful enough to avoid emitting a few extra bytes in certain circumstances, so these tests fail.  The failures take the form of additional elements in the ;-delimited character attribute lists.  For example, \\x1b[0;31;46m might be emitted instead of \\x[46m, even if 31 has already been activated and no conflicting attributes are set which need to be cleared."
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_text.py", line 95, in testNesting
    '\x1b[1mHello, \x1b[4mworld.')
<class 'twisted.trial.unittest.FailTest'>: '\x1b[1mHello, \x1b[1;4mworld.' != '\x1b[1mHello, \x1b[4mworld.'
===============================================================================
[TODO]: twisted.words.test.test_jabbererror.ParseErrorTest.testTextLangInherited

Reason: 'xml:lang inheritance not implemented'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/words/test/test_jabbererror.py", line 116, in testTextLangInherited
    self.assertEqual('en_US', result['textLang'])
<class 'twisted.trial.unittest.FailTest'>: 'en_US' != None
===============================================================================
[TODO]: twisted.web2.dav.test.test_lock.LOCK_UNLOCK.test_LOCK_UNLOCK

Reason: 'LOCK/UNLOCK unimplemented'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web2/dav/test/test_lock.py", line 51, in test_LOCK_UNLOCK
    raise SkipTest("test unimplemented")
<class 'twisted.trial.unittest.SkipTest'>: test unimplemented
===============================================================================
[TODO]: twisted.web2.dav.test.test_options.OPTIONS.test_DAV2

Reason: 'DAV level 2 unimplemented'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web2/dav/test/test_options.py", line 54, in doTest
    self.assertIn(level, dav, "no DAV level %s header" % (level,))
<class 'twisted.trial.unittest.FailTest'>: no DAV level 2 header
===============================================================================
[TODO]: twisted.web.test.test_static.Range.testBodyLength

Reason: 'No range support yet.'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web/test/test_static.py", line 52, in testBodyLength
    self.assertEquals(len(self.request._written), 2000)
<class 'twisted.trial.unittest.FailTest'>: 8000 != 2000
===============================================================================
[TODO]: twisted.web.test.test_static.Range.testContentLength

Reason: 'No range support yet.'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web/test/test_static.py", line 58, in testContentLength
    self.assertEquals(self.request._setHeaders['content-length'], ['2000'])
<class 'twisted.trial.unittest.FailTest'>: ['8000'] != ['2000']
===============================================================================
[TODO]: twisted.web.test.test_static.Range.testContentRange

Reason: 'No range support yet.'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web/test/test_static.py", line 64, in testContentRange
    self.assertEquals(self.request._setHeaders.get('content-range'), ['bytes 0-1999/8000'])
<class 'twisted.trial.unittest.FailTest'>: None != ['bytes 0-1999/8000']
===============================================================================
[TODO]: twisted.web.test.test_xml.MicroDOMTest.testLaterCloserDL2

Reason: 'unclosed <p> messes it up.'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web/test/test_xml.py", line 455, in testLaterCloserDL2
    self.assertEquals(expected, actual)
<class 'twisted.trial.unittest.FailTest'>: '<dl><dt>word</dt><dd>definition<p>more definition</p></dd><dt>word</dt></dl>' != '<dl><dt>word</dt><dd>definition<p>more definition</p><dt>word</dt></dd></dl>'
===============================================================================
[TODO]: twisted.web.test.test_xml.MicroDOMTest.testLaterCloserTable

Reason: 'Table parsing needs to be fixed.'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web/test/test_xml.py", line 427, in testLaterCloserTable
    self.assertEquals(expected, actual)
<class 'twisted.trial.unittest.FailTest'>: '<table><tr><th>name</th><th>value</th><th>comment</th></tr><tr><th>this</th><td>tag</td><td>soup</td></tr><tr><th>must</th><td>be</td><td>handled</td></tr></table>' != '<table><tr><th>name</th><th>value</th><th>comment<tr><th>this<td>tag</td><td>soup<tr><th>must<td>be</td><td>handled</td></th></tr></td></th></tr></th></tr></table>'
===============================================================================
[TODO]: twisted.web.test.test_xml.MicroDOMTest.testSpacing

Reason: 'AAARGH white space swallowing screws this up'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/web/test/test_xml.py", line 396, in testSpacing
    self.assertEquals(expected, actual)
<class 'twisted.trial.unittest.FailTest'>: '<p><q>smart</q> <code>HairDryer</code></p>' != '<p><q>smart</q><code>HairDryer</code></p>'
===============================================================================
[TODO]: twisted.test.test_failure.FailureTestCase.testLackOfTB

Reason: "the traceback is not preserved, exarkun said he'll try to fix this! god knows how"
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_failure.py", line 88, in testLackOfTB
    self.assertEquals(innerline, '1/0')
<class 'twisted.trial.unittest.FailTest'>: 'raise self.type, self.value, self.tb' != '1/0'
===============================================================================
[TODO]: twisted.test.test_jelly.JellyTestCase.testNewStyle

Reason: 'jelly does not support new-style classes yet'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_jelly.py", line 94, in testNewStyle
    c = jelly.jelly(n)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 892, in jelly
    return _Jellier(taster, persistentStore, invoker).jelly(object)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 498, in jelly
    raise NotImplementedError("Don't know the type: %s" % objType)
<type 'exceptions.NotImplementedError'>: Don't know the type: <class 'twisted.test.test_jelly.NewStyle'>
===============================================================================
[TODO]: twisted.test.test_rebuild.NewStyleTestCase.testSlots

Reason: 'New Style classes are poorly supported'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_rebuild.py", line 139, in testSlots
    rebuild.updateInstance(self.m.SlottedClass())
  File "/home/scmikes/python2.5/trunk/twisted/python/rebuild.py", line 99, in updateInstance
    self.__class__ = latestClass(self.__class__)
<type 'exceptions.TypeError'>: __class__ assignment: 'SlottedClass' object layout differs from 'SlottedClass'
===============================================================================
[TODO]: twisted.test.test_rebuild.NewStyleTestCase.testTypeSubclass

Reason: 'New Style classes are poorly supported'
Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_rebuild.py", line 143, in testTypeSubclass
    rebuild.updateInstance(self.m.ListSubclass())
  File "/home/scmikes/python2.5/trunk/twisted/python/rebuild.py", line 99, in updateInstance
    self.__class__ = latestClass(self.__class__)
<type 'exceptions.TypeError'>: __class__ assignment: 'ListSubclass' object layout differs from 'ListSubclass'
===============================================================================
[FAIL]: twisted.conch.test.test_cftp.TestOurServerBatchFile.testBatchFile

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 347, in testBatchFile
    self.failUnlessEqual(res[3:-2], ['testDirectory', 'testRemoveFile', 'testRenameFile', 'testfile1'])
<class 'twisted.trial.unittest.FailTest'>: [] != ['testDirectory', 'testRemoveFile', 'testRenameFile', 'testfile1']
===============================================================================
[FAIL]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testChAttrs

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 185, in testChAttrs
    self.failUnless(lsRes.startswith('-rw-r--r--'), lsRes)
<class 'twisted.trial.unittest.FailTest'>: remote error 4: scan directory failed
===============================================================================
[FAIL]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testDirectory

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 273, in testDirectory
    self.failUnless(lslRes.startswith('d'), lslRes)
<class 'twisted.trial.unittest.FailTest'>: remote error 4: scan directory failed
===============================================================================
[FAIL]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testGet

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 223, in testGet
    self.testDir + '/test file2', "get failed")
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 216, in _failUnlessFilesEqual
    self.failUnlessEqual(f1, f2, msg)
<class 'twisted.trial.unittest.FailTest'>: get failed
===============================================================================
[FAIL]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testLink

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 267, in testLink
    self.failUnless(lslRes.startswith('l'), 'link failed')
<class 'twisted.trial.unittest.FailTest'>: link failed
===============================================================================
[FAIL]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testList

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 196, in testList
    'testRenameFile', 'testfile1'])
<class 'twisted.trial.unittest.FailTest'>: ['remote error 4: scan directory failed'] != ['testDirectory', 'testRemoveFile', 'testRenameFile', 'testfile1']
===============================================================================
[FAIL]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testRename

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 282, in testRename
    self.failUnlessEqual(lsRes, ['testfile2'])
<class 'twisted.trial.unittest.FailTest'>: ['remote error 4: scan directory failed'] != ['testfile2']
===============================================================================
[FAIL]: twisted.conch.test.test_manhole.ManholeLoopbackSSH.testException

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_manhole.py", line 134, in finished
    ">>> done"])
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_recvline.py", line 382, in _assertBuffer
    str(expectedLines[max(0, i-1):i+1]))
<class 'twisted.trial.unittest.FailTest'>: ['Traceback (most recent call last):', '  File "<console>", line 1, in <module>'] != ['Traceback (most recent call last):', '  File "<console>", line 1, in ?']
===============================================================================
[FAIL]: twisted.conch.test.test_manhole.ManholeLoopbackStdio.testControlBackslash

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'twisted.internet.error.ProcessDone'>> not expected ((<class 'twisted.internet.error.ConnectionDone'>,))
===============================================================================
[FAIL]: twisted.conch.test.test_manhole.ManholeLoopbackStdio.testControlD

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/internet/defer.py", line 623, in _deferGenerator
    result = g.next()
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_manhole.py", line 193, in testControlD
    disconnected.getResult()
  File "/home/scmikes/python2.5/trunk/twisted/internet/defer.py", line 609, in getResult
    self.result.raiseException()
  File "/home/scmikes/python2.5/trunk/twisted/internet/defer.py", line 317, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'twisted.internet.error.ProcessDone'>> not expected ((<class 'twisted.internet.error.ConnectionDone'>,))
===============================================================================
[FAIL]: twisted.conch.test.test_manhole.ManholeLoopbackStdio.testException

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_manhole.py", line 134, in finished
    ">>> done"])
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_recvline.py", line 382, in _assertBuffer
    str(expectedLines[max(0, i-1):i+1]))
<class 'twisted.trial.unittest.FailTest'>: ['Traceback (most recent call last):', '  File "<console>", line 1, in <module>'] != ['Traceback (most recent call last):', '  File "<console>", line 1, in ?']
===============================================================================
[FAIL]: twisted.conch.test.test_manhole.ManholeLoopbackTelnet.testException

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_manhole.py", line 134, in finished
    ">>> done"])
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_recvline.py", line 382, in _assertBuffer
    str(expectedLines[max(0, i-1):i+1]))
<class 'twisted.trial.unittest.FailTest'>: ['Traceback (most recent call last):', '  File "<console>", line 1, in <module>'] != ['Traceback (most recent call last):', '  File "<console>", line 1, in ?']
===============================================================================
[FAIL]: twisted.vfs.test.test_ftp.FTPAdapterTestCase.testMKD

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'twisted.vfs.ivfs.AlreadyExistsError'>> not expected ((<class 'twisted.vfs.ivfs.VFSError'>, 'MKD newdir twice should cause a failure'))
===============================================================================
[FAIL]: twisted.pb.test.test_copyable.Copyable.testCopy4

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_copyable.py", line 212, in _testCopy4_2
    self.failUnlessSubstring("unknown attribute 'bad'", str(why))
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 256, in failUnlessSubstring
    return self.failUnlessIn(substring, astring, msg)
<class 'twisted.trial.unittest.FailTest'>: "unknown attribute 'bad'" not in "[Failure instance: Traceback: <class 'twisted.pb.tokens.Violation'>: Violation (at <RootUnslicer>.<error-1>.???.[0]): ('ABORT received',)\n/home/scmikes/python2.5/trunk/twisted/internet/defer.py:304:_startRunCallbacks\n/home/scmikes/python2.5/trunk/twisted/internet/defer.py:317:_runCallbacks\n/home/scmikes/python2.5/trunk/twisted/pb/test/common.py:32:_write\n/home/scmikes/python2.5/trunk/twisted/pb/banana.py:493:dataReceived\n--- <exception caught here> ---\n/home/scmikes/python2.5/trunk/twisted/pb/banana.py:706:handleData\n]"
===============================================================================
[FAIL]: twisted.pb.test.test_pb.TestCall.testFail1

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_pb.py", line 371, in _testFail1_1
    "wrong exception type: %s" % f)
<class 'twisted.trial.unittest.FailTest'>: wrong exception type: [Failure instance: Traceback: <class 'twisted.pb.tokens.Violation'>: Violation (at <RootUnslicer>.<error-0>.???.[0]): ('ABORT received',)
/home/scmikes/python2.5/trunk/twisted/internet/defer.py:304:_startRunCallbacks
/home/scmikes/python2.5/trunk/twisted/internet/defer.py:317:_runCallbacks
/home/scmikes/python2.5/trunk/twisted/pb/test/common.py:32:_write
/home/scmikes/python2.5/trunk/twisted/pb/banana.py:493:dataReceived
--- <exception caught here> ---
/home/scmikes/python2.5/trunk/twisted/pb/banana.py:706:handleData
]
===============================================================================
[FAIL]: twisted.pb.test.test_pb.TestCall.testFail2

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_pb.py", line 387, in _testFail2_1
    "wrong exception type: %s" % f.type)
<class 'twisted.trial.unittest.FailTest'>: wrong exception type: <class 'twisted.pb.tokens.Violation'>
===============================================================================
[FAIL]: twisted.pb.test.test_pb.TestCall.testFail3

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_pb.py", line 404, in _testFail3_1
    "wrong exception type: %s" % f.type)
<class 'twisted.trial.unittest.FailTest'>: wrong exception type: <class 'twisted.pb.tokens.Violation'>
===============================================================================
[FAIL]: twisted.pb.test.test_pb.TestCall.testFailWrongArgsRemote1

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_pb.py", line 517, in _testFailWrongArgsRemote1_1
    f.value)
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 256, in failUnlessSubstring
    return self.failUnlessIn(substring, astring, msg)
<class 'twisted.trial.unittest.FailTest'>: 'STRING token rejected by IntegerConstraint' not in Violation('ABORT received',)
===============================================================================
[FAIL]: twisted.pb.test.test_pb.TestCall.testFailWrongMethodRemote

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_pb.py", line 459, in _testFailWrongMethodRemote_1
    str(f))
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 256, in failUnlessSubstring
    return self.failUnlessIn(substring, astring, msg)
<class 'twisted.trial.unittest.FailTest'>: "method 'bogus' not defined in RIMyTarget" not in "[Failure instance: Traceback: <class 'twisted.pb.tokens.Violation'>: Violation (at <RootUnslicer>.<error-0>.???.[0]): ('ABORT received',)\n/home/scmikes/python2.5/trunk/twisted/internet/defer.py:304:_startRunCallbacks\n/home/scmikes/python2.5/trunk/twisted/internet/defer.py:317:_runCallbacks\n/home/scmikes/python2.5/trunk/twisted/pb/test/common.py:32:_write\n/home/scmikes/python2.5/trunk/twisted/pb/banana.py:493:dataReceived\n--- <exception caught here> ---\n/home/scmikes/python2.5/trunk/twisted/pb/banana.py:706:handleData\n]"
===============================================================================
[FAIL]: twisted.pb.test.test_pb.TestCall.testFailWrongReturnRemote

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_pb.py", line 530, in _testFailWrongReturnRemote_1
    self.failUnlessSubstring("in outbound method results", f.value)
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 256, in failUnlessSubstring
    return self.failUnlessIn(substring, astring, msg)
<class 'twisted.trial.unittest.FailTest'>: 'in outbound method results' not in Violation('ABORT received',)
===============================================================================
[FAIL]: twisted.pb.test.test_pb.TestService.testBadMethod2

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/test/test_pb.py", line 976, in _testBadMethod2_eb
    self.failUnlessEqual(f.type, 'exceptions.AttributeError')
<class 'twisted.trial.unittest.FailTest'>: <class 'twisted.pb.tokens.Violation'> != 'exceptions.AttributeError'
===============================================================================
[FAIL]: twisted.web.test.test_xmlrpc.XMLRPCClientErrorHandling.testErroneousResponse

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'xml.parsers.expat.ExpatError'>> not expected ((<type 'exceptions.Exception'>,))
===============================================================================
[FAIL]: twisted.test.test_ftp.BasicFTPServerTestCase.testAnonymousLoginDenied

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'twisted.trial.unittest.FailTest'>> not expected ((<class 'twisted.protocols.ftp.CommandFailed'>,))
===============================================================================
[FAIL]: twisted.test.test_ftp.BasicFTPServerTestCase.testBadCommandArgs

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'twisted.trial.unittest.FailTest'>> not expected ((<class 'twisted.protocols.ftp.CommandFailed'>,))
===============================================================================
[FAIL]: twisted.test.test_ftp.BasicFTPServerTestCase.testRETRBeforePORT

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_ftp.py", line 135, in failed
    expectedResponse, exception.args[0])
<class 'twisted.trial.unittest.FailTest'>: ['503 Incorrect sequence of commands: PORT or PASV required before RETR'] != ['550 Requested action not taken: internal server error']
===============================================================================
[FAIL]: twisted.test.test_ftp.BasicFTPServerTestCase.testSTORBeforePORT

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_ftp.py", line 135, in failed
    expectedResponse, exception.args[0])
<class 'twisted.trial.unittest.FailTest'>: ['503 Incorrect sequence of commands: PORT or PASV required before STOR'] != ['550 Requested action not taken: internal server error']
===============================================================================
[FAIL]: twisted.test.test_ftp.BasicFTPServerTestCase.testUnknownCommand

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_ftp.py", line 135, in failed
    expectedResponse, exception.args[0])
<class 'twisted.trial.unittest.FailTest'>: ["502 Command 'GIBBERISH' not implemented"] != ['550 Requested action not taken: internal server error']
===============================================================================
[FAIL]: twisted.test.test_ident.ServerParserTestCase.testErrors

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_ident.py", line 88, in testErrors
    self.assertEquals(L[1], '432, 210 : ERROR : NO-USER')
<class 'twisted.trial.unittest.FailTest'>: '432, 210 : ERROR : UNKNOWN-ERROR' != '432, 210 : ERROR : NO-USER'
===============================================================================
[FAIL]: twisted.test.test_udp.MulticastTestCase.testLoopback

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_udp.py", line 636, in testLoopback
    self.assertEquals(len(self.server.packets), 1)
<class 'twisted.trial.unittest.FailTest'>: 0 != 1
===============================================================================
[FAIL]: twisted.mail.test.test_mail.MaildirAppendStringTestCase.testAppend

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <type 'exceptions.OSError'>> not expected ((<type 'exceptions.Exception'>,))
===============================================================================
[FAIL]: twisted.trial.test.test_output.TestImportErrors.test_badimport

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 112, in test_badimport
    self.failIfIn(d, '<module')
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 59, in failIfIn
    containee, container, *args, **kwargs)
<class 'twisted.trial.unittest.FailTest'>: '<module' in 'Running 0 tests.\n[ERROR]\n===============================================================================\n[ERROR]: package.test_import_module\n\nTraceback (most recent call last):\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName\n    thing = self.findByName(name)\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName\n    return reflect.namedAny(name)\n  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny\n    topLevelPackage = __import__(trialname)\n  File "_testImportErrors/package/test_import_module.py", line 1, in <module>\n    import frotz\n  File "_testImportErrors/package/frotz.py", line 1, in <module>\n    frotz\n<type \'exceptions.NameError\'>: name \'frotz\' is not defined\n-------------------------------------------------------------------------------\nRan 0 tests in 0.004s\n\nFAILED (errors=1)\n'
===============================================================================
[FAIL]: twisted.trial.test.test_output.TestImportErrors.test_badmodule

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 104, in test_badmodule
    self.failIfIn(d, '<module')
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 59, in failIfIn
    containee, container, *args, **kwargs)
<class 'twisted.trial.unittest.FailTest'>: '<module' in 'Running 0 tests.\n[ERROR]\n===============================================================================\n[ERROR]: package.test_bad_module\n\nTraceback (most recent call last):\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName\n    thing = self.findByName(name)\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName\n    return reflect.namedAny(name)\n  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny\n    topLevelPackage = __import__(trialname)\n  File "_testImportErrors/package/test_bad_module.py", line 1, in <module>\n    raise ZeroDivisionError("fake error")\n<type \'exceptions.ZeroDivisionError\'>: fake error\n-------------------------------------------------------------------------------\nRan 0 tests in 0.003s\n\nFAILED (errors=1)\n'
===============================================================================
[FAIL]: twisted.trial.test.test_output.TestImportErrors.test_nonRecurseImportErrors

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 138, in test_nonRecurseImportErrors
    self.failIfIn(d, '<module')
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 59, in failIfIn
    containee, container, *args, **kwargs)
<class 'twisted.trial.unittest.FailTest'>: '<module' in 'Running 0 tests.\n[ERROR]\n===============================================================================\n[ERROR]: package2.test_module\n\nTraceback (most recent call last):\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName\n    thing = self.findByName(name)\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName\n    return reflect.namedAny(name)\n  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny\n    topLevelPackage = __import__(trialname)\n  File "_testImportErrors/package2/test_module.py", line 1, in <module>\n    import frotz\n<type \'exceptions.ImportError\'>: No module named frotz\n-------------------------------------------------------------------------------\nRan 0 tests in 0.002s\n\nFAILED (errors=1)\n'
===============================================================================
[FAIL]: twisted.trial.test.test_output.TestImportErrors.test_recurseImport

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 120, in test_recurseImport
    self.failIfIn(d, '<module')
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 59, in failIfIn
    containee, container, *args, **kwargs)
<class 'twisted.trial.unittest.FailTest'>: '<module' in 'Running 2 tests.\n[ERROR]package.test_dos_module.FooTest.testFoo ... [OK]\n[ERROR]package.test_module.FooTest.testFoo ... [OK]\n\n===============================================================================\n[ERROR]: package.test_bad_module\n\nTraceback (most recent call last):\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName\n    thing = self.findByName(name)\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName\n    return reflect.namedAny(name)\n  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny\n    topLevelPackage = __import__(trialname)\n  File "_testImportErrors/package/test_bad_module.py", line 1, in <module>\n    raise ZeroDivisionError("fake error")\n<type \'exceptions.ZeroDivisionError\'>: fake error\n===============================================================================\n[ERROR]: package.test_import_module\n\nTraceback (most recent call last):\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName\n    thing = self.findByName(name)\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName\n    return reflect.namedAny(name)\n  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny\n    topLevelPackage = __import__(trialname)\n  File "_testImportErrors/package/test_import_module.py", line 1, in <module>\n    import frotz\n  File "_testImportErrors/package/frotz.py", line 1, in <module>\n    frotz\n<type \'exceptions.NameError\'>: name \'frotz\' is not defined\n-------------------------------------------------------------------------------\nRan 2 tests in 0.005s\n\nFAILED (errors=2, successes=2)\n'
===============================================================================
[FAIL]: twisted.trial.test.test_output.TestImportErrors.test_recurseImportErrors

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 130, in test_recurseImportErrors
    self.failIfIn(d, '<module')
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_output.py", line 59, in failIfIn
    containee, container, *args, **kwargs)
<class 'twisted.trial.unittest.FailTest'>: '<module' in 'Running 0 tests.\n[ERROR]\n===============================================================================\n[ERROR]: package2.test_module\n\nTraceback (most recent call last):\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName\n    thing = self.findByName(name)\n  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName\n    return reflect.namedAny(name)\n  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny\n    topLevelPackage = __import__(trialname)\n  File "_testImportErrors/package2/test_module.py", line 1, in <module>\n    import frotz\n<type \'exceptions.ImportError\'>: No module named frotz\n-------------------------------------------------------------------------------\nRan 0 tests in 0.002s\n\nFAILED (errors=1)\n'
===============================================================================
[FAIL]: twisted.trial.test.test_reporter.FormatFailures.test_formatDefault

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_reporter.py", line 165, in test_formatDefault
    'RuntimeError: foo'], tb.splitlines())
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_reporter.py", line 24, in stringComparison
    self.assertSubstring(exp, out)
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 256, in failUnlessSubstring
    return self.failUnlessIn(substring, astring, msg)
<class 'twisted.trial.unittest.FailTest'>: 'RuntimeError: foo' not in "<type 'exceptions.RuntimeError'>: foo"
===============================================================================
[FAIL]: twisted.trial.test.test_reporter.TestErrorReporting.testFormatErroredMethod

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_reporter.py", line 58, in testFormatErroredMethod
    self.stringComparison(match, output)
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_reporter.py", line 24, in stringComparison
    self.assertSubstring(exp, out)
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 256, in failUnlessSubstring
    return self.failUnlessIn(substring, astring, msg)
<class 'twisted.trial.unittest.FailTest'>: 'twisted.trial.test.erroneous.FoolishError: I am a broken setUp method' not in "<class 'twisted.trial.test.erroneous.FoolishError'>: I am a broken setUp method"
===============================================================================
[FAIL]: twisted.trial.test.test_reporter.TestErrorReporting.testFormatFailedMethod

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_reporter.py", line 72, in testFormatFailedMethod
    self.stringComparison(match, output)
  File "/home/scmikes/python2.5/trunk/twisted/trial/test/test_reporter.py", line 24, in stringComparison
    self.assertSubstring(exp, out)
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 256, in failUnlessSubstring
    return self.failUnlessIn(substring, astring, msg)
<class 'twisted.trial.unittest.FailTest'>: 'twisted.trial.unittest.FailTest: I fail' not in "<class 'twisted.trial.unittest.FailTest'>: I fail"
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerBatchFile.testBatchFile

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 311, in _cbSendDirectory
    data += self._packAttributes(attrs)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testChAttrs

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/internet/defer.py", line 107, in maybeDeferred
    result = f(*args, **kw)
  File "/home/scmikes/python2.5/trunk/twisted/conch/unix.py", line 356, in openDirectory
    return UnixSFTPDirectory(self, self._absPath(path))
  File "/home/scmikes/python2.5/trunk/twisted/conch/unix.py", line 439, in __init__
    self.files = server.avatar._runAsUser(os.listdir, directory)
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_filetransfer.py", line 44, in _runAsUser
    r = func(*args, **kw)
<type 'exceptions.OSError'>: [Errno 20] Not a directory: '/home/scmikes/python2.5/trunk/_trial_temp/twisted.conch.test.test_cftp/TestOurServerCmdLineClient/testRename/niR-1H/temp/extra/testfile1'
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testDirectory

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 311, in _cbSendDirectory
    data += self._packAttributes(attrs)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testGet

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 342, in _cbStat
    data = requestId + self._packAttributes(result)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testList

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 311, in _cbSendDirectory
    data += self._packAttributes(attrs)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testRename

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 311, in _cbSendDirectory
    data += self._packAttributes(attrs)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testWildcardGet

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 234, in testWildcardGet
    'testRemoveFile', 'testRemoveFile get failed')
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_cftp.py", line 215, in _failUnlessFilesEqual
    f2 = file(name2).read()
<type 'exceptions.IOError'>: [Errno 2] No such file or directory: 'testRemoveFile'
===============================================================================
[ERROR]: twisted.conch.test.test_cftp.TestOurServerCmdLineClient.testWildcardGet

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 311, in _cbSendDirectory
    data += self._packAttributes(attrs)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testDirectoryCreation

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 342, in _cbStat
    data = requestId + self._packAttributes(result)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testLinkSharesAttrs

Traceback (most recent call last):
Failure: <class 'twisted.conch.ssh.filetransfer.SFTPError'>: SFTPError 4: stat/lstat failed
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testLinkSharesAttrs

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 342, in _cbStat
    data = requestId + self._packAttributes(result)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testOpenDirectory

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/test/test_filetransfer.py", line 312, in _checkFiles
    fs = list(zip(*files)[0])
<type 'exceptions.IndexError'>: list index out of range
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testOpenDirectory

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 311, in _cbSendDirectory
    data += self._packAttributes(attrs)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testOpenFileAttributes

Traceback (most recent call last):
Failure: <class 'twisted.conch.ssh.filetransfer.SFTPError'>: SFTPError 4: fstat failed
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testOpenFileAttributes

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 342, in _cbStat
    data = requestId + self._packAttributes(result)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testOpenFileSetAttrs

Traceback (most recent call last):
Failure: <class 'twisted.conch.ssh.filetransfer.SFTPError'>: SFTPError 4: fstat failed
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testOpenFileSetAttrs

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 342, in _cbStat
    data = requestId + self._packAttributes(result)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testRemoveFile

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 342, in _cbStat
    data = requestId + self._packAttributes(result)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testRenameFile

Traceback (most recent call last):
Failure: <class 'twisted.conch.ssh.filetransfer.SFTPError'>: SFTPError 4: stat/lstat failed
===============================================================================
[ERROR]: twisted.conch.test.test_filetransfer.TestOurServerOurClient.testRenameFile

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 342, in _cbStat
    data = requestId + self._packAttributes(result)
  File "/home/scmikes/python2.5/trunk/twisted/conch/ssh/filetransfer.py", line 103, in _packAttributes
    data += struct.pack('!2L', attrs['atime'], attrs['mtime'])
  File "/usr/local/lib/python2.5/struct.py", line 63, in pack
    return o.pack(*args)
<type 'exceptions.TypeError'>: unsupported operand type(s) for &: 'float' and 'long'
===============================================================================
[ERROR]: twisted.conch.test.test_manhole.ManholeLoopbackStdio.testControlBackslash

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'twisted.internet.error.ProcessDone'>> not expected ((<class 'twisted.internet.error.ConnectionDone'>,))
===============================================================================
[ERROR]: twisted.conch.test.test_manhole.ManholeLoopbackStdio.testControlD

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/unittest.py", line 251, in _eb
    % (failure, expectedFailures))
<class 'twisted.trial.unittest.FailTest'>: <twisted.python.failure.Failure <class 'twisted.internet.error.ProcessDone'>> not expected ((<class 'twisted.internet.error.ConnectionDone'>,))
===============================================================================
[ERROR]: twisted.words.test.test_jabbercomponent

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName
    thing = self.findByName(name)
  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName
    return reflect.namedAny(name)
  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny
    topLevelPackage = __import__(trialname)
  File "/home/scmikes/python2.5/trunk/twisted/words/test/test_jabbercomponent.py", line 8, in <module>
    from twisted.words.protocols.jabber.component import ConnectComponentAuthenticator
  File "/home/scmikes/python2.5/trunk/twisted/words/protocols/jabber/component.py", line 10, in <module>
    from twisted.words.protocols.jabber import jstrports, xmlstream
  File "/home/scmikes/python2.5/trunk/twisted/words/protocols/jabber/xmlstream.py", line 13, in <module>
    from OpenSSL import SSL
<type 'exceptions.ImportError'>: No module named OpenSSL
===============================================================================
[ERROR]: twisted.words.test.test_jabbererror.StreamErrorTest.testGetElementPlain

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/words/test/test_jabbererror.py", line 47, in testGetElementPlain
    element = e.getElement()
  File "/home/scmikes/python2.5/trunk/twisted/words/protocols/jabber/error.py", line 90, in getElement
    from twisted.words.protocols.jabber.xmlstream import NS_STREAMS
  File "/home/scmikes/python2.5/trunk/twisted/words/protocols/jabber/xmlstream.py", line 13, in <module>
    from OpenSSL import SSL
<type 'exceptions.ImportError'>: No module named OpenSSL
===============================================================================
[ERROR]: twisted.words.test.test_jabberxmlstream

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName
    thing = self.findByName(name)
  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName
    return reflect.namedAny(name)
  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny
    topLevelPackage = __import__(trialname)
  File "/home/scmikes/python2.5/trunk/twisted/words/test/test_jabberxmlstream.py", line 3, in <module>
    from twisted.words.protocols.jabber import error, xmlstream
  File "/home/scmikes/python2.5/trunk/twisted/words/protocols/jabber/xmlstream.py", line 13, in <module>
    from OpenSSL import SSL
<type 'exceptions.ImportError'>: No module named OpenSSL
===============================================================================
[ERROR]: twisted.words.test.test_msn

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 343, in loadByName
    thing = self.findByName(name)
  File "/home/scmikes/python2.5/trunk/twisted/trial/runner.py", line 252, in findByName
    return reflect.namedAny(name)
  File "/home/scmikes/python2.5/trunk/twisted/python/reflect.py", line 352, in namedAny
    topLevelPackage = __import__(trialname)
  File "/home/scmikes/python2.5/trunk/twisted/words/test/test_msn.py", line 24, in <module>
    from twisted.words.protocols import msn
  File "/home/scmikes/python2.5/trunk/twisted/words/protocols/msn.py", line 85, in <module>
    from twisted.internet.ssl import ClientContextFactory
  File "/home/scmikes/python2.5/trunk/twisted/internet/ssl.py", line 47, in <module>
    from OpenSSL import SSL
<type 'exceptions.ImportError'>: No module named OpenSSL
===============================================================================
[ERROR]: twisted.pb.test.test_copyable.Copyable.testCopy4

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-1>.<twisted.python.failure.Failure>.??): ("cannot serialize <class 'twisted.pb.tokens.Violation'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_copyable.Copyable.testFailure1

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<call-0-1-set>.<twisted.python.failure.Failure>.??): ("cannot serialize <type 'exceptions.RuntimeError'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_copyable.Copyable.testFailure2

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<call-0-1-set>.<twisted.python.failure.Failure>.??): ("cannot serialize <type 'exceptions.RuntimeError'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_pb.TestCall.testFail1

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-0>.<twisted.python.failure.Failure>.??): ("cannot serialize <type 'exceptions.ValueError'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_pb.TestCall.testFail2

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-0>.<twisted.python.failure.Failure>.??): ("cannot serialize <type 'exceptions.TypeError'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_pb.TestCall.testFail3

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-0>.<twisted.python.failure.Failure>.??): ("cannot serialize <type 'exceptions.AttributeError'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_pb.TestCall.testFailWrongArgsRemote1

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-0>.<twisted.python.failure.Failure>.??): ("cannot serialize <class 'twisted.pb.tokens.Violation'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_pb.TestCall.testFailWrongMethodRemote

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-0>.<twisted.python.failure.Failure>.??): ("cannot serialize <class 'twisted.pb.tokens.Violation'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_pb.TestCall.testFailWrongReturnRemote

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-0>.<twisted.python.failure.Failure>.??): ("cannot serialize <class 'twisted.pb.tokens.Violation'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.pb.test.test_pb.TestService.testBadMethod2

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 161, in produce
    slicer = self.newSlicerFor(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/banana.py", line 260, in newSlicerFor
    return topSlicer.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 56, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 134, in slicerForObject
    return self.parent.slicerForObject(obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/broker.py", line 137, in slicerForObject
    return slicer.RootSlicer.slicerForObject(self, obj)
  File "/home/scmikes/python2.5/trunk/twisted/pb/slicer.py", line 328, in slicerForObject
    raise Violation("cannot serialize %s (%s)" % (obj, name))
<class 'twisted.pb.tokens.Violation'>: Violation (at <RootSlicer>.<error-1>.<twisted.python.failure.Failure>.??): ("cannot serialize <type 'exceptions.AttributeError'> (<type 'type'>)",)
===============================================================================
[ERROR]: twisted.test.test_failure.FailureTestCase.testFailAndTrap

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_failure.py", line 30, in testFailAndTrap
    raise NotImplementedError('test')
<type 'exceptions.NotImplementedError'>: test
===============================================================================
[ERROR]: twisted.test.test_ftp.BasicFTPServerTestCase.testAnonymousLoginDenied

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/protocols/ftp.py", line 722, in _ebLogin
    raise AuthorizationError
<class 'twisted.protocols.ftp.AuthorizationError'>: 
===============================================================================
[ERROR]: twisted.test.test_ftp.BasicFTPServerTestCase.testBadCommandArgs

Traceback (most recent call last):
Failure: <class 'twisted.protocols.ftp.CmdNotImplementedForArgError'>: z
===============================================================================
[ERROR]: twisted.test.test_ftp.BasicFTPServerTestCase.testRETRBeforePORT

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/internet/defer.py", line 107, in maybeDeferred
    result = f(*args, **kw)
  File "/home/scmikes/python2.5/trunk/twisted/protocols/ftp.py", line 668, in processCommand
    return method(*params)
  File "/home/scmikes/python2.5/trunk/twisted/protocols/ftp.py", line 884, in ftp_RETR
    raise BadCmdSequenceError('PORT or PASV required before RETR')
<class 'twisted.protocols.ftp.BadCmdSequenceError'>: PORT or PASV required before RETR
===============================================================================
[ERROR]: twisted.test.test_ftp.BasicFTPServerTestCase.testSTORBeforePORT

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/internet/defer.py", line 107, in maybeDeferred
    result = f(*args, **kw)
  File "/home/scmikes/python2.5/trunk/twisted/protocols/ftp.py", line 668, in processCommand
    return method(*params)
  File "/home/scmikes/python2.5/trunk/twisted/protocols/ftp.py", line 942, in ftp_STOR
    raise BadCmdSequenceError('PORT or PASV required before STOR')
<class 'twisted.protocols.ftp.BadCmdSequenceError'>: PORT or PASV required before STOR
===============================================================================
[ERROR]: twisted.test.test_ftp.BasicFTPServerTestCase.testUnknownCommand

Traceback (most recent call last):
Failure: <class 'twisted.protocols.ftp.CmdNotImplementedError'>: GIBBERISH
===============================================================================
[ERROR]: twisted.test.test_ident.ServerParserTestCase.testErrors

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/internet/defer.py", line 107, in maybeDeferred
    result = f(*args, **kw)
  File "/home/scmikes/python2.5/trunk/twisted/test/test_ident.py", line 70, in lookup
    raise self.exceptionType()
<class 'twisted.protocols.ident.NoUser'>: NO-USER
===============================================================================
[ERROR]: twisted.test.test_pb.BrokerTestCase.testTooManyRefs

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_pb.py", line 490, in testTooManyRefs
    pump.pump()
  File "/home/scmikes/python2.5/trunk/twisted/test/test_pb.py", line 91, in pump
    self.server.dataReceived(byte)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 184, in dataReceived
    gotItem(item)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 114, in gotItem
    self.callExpressionReceived(item)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 81, in callExpressionReceived
    self.expressionReceived(obj)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 523, in expressionReceived
    method(*sexp[1:])
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 834, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 860, in _recvMessage
    self._sendError(CopyableFailure(e), requestID)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 917, in _sendError
    self.sendCall("error", requestID, self.serialize(fail))
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 771, in serialize
    return jelly(object, self.security, None, self)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 892, in jelly
    return _Jellier(taster, persistentStore, invoker).jelly(object)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 417, in jelly
    return obj.jellyFor(self)
  File "/home/scmikes/python2.5/trunk/twisted/spread/flavors.py", line 308, in jellyFor
    sxp.extend([t, jellier.jelly(state)])
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 477, in jelly
    sxp.append([self.jelly(key), self.jelly(val)])
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 469, in jelly
    sxp.append(self.jelly(item))
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 505, in jelly
    (objType, obj))
<class 'twisted.spread.jelly.InsecureJelly'>: Type not allowed for object: <type 'type'> <class 'twisted.spread.pb.Error'>
===============================================================================
[ERROR]: twisted.test.test_pb.NewCredTestCase.testBadLogin

Traceback (most recent call last):
Failure: <class 'twisted.internet.defer.TimeoutError'>: <twisted.test.test_pb.NewCredTestCase testMethod=testBadLogin> (testBadLogin) still running at 120.0 secs
===============================================================================
[ERROR]: twisted.test.test_pb.NewCredTestCase.testBadLogin

Traceback (most recent call last):
Failure: <class 'twisted.cred.error.UnauthorizedLogin'>: 
===============================================================================
[ERROR]: twisted.test.test_pbfailure.PBFailureTest.testCopiedFailureLogging

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/internet/selectreactor.py", line 139, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/home/scmikes/python2.5/trunk/twisted/internet/tcp.py", line 348, in doRead
    return self.protocol.dataReceived(data)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 184, in dataReceived
    gotItem(item)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 114, in gotItem
    self.callExpressionReceived(item)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 81, in callExpressionReceived
    self.expressionReceived(obj)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 523, in expressionReceived
    method(*sexp[1:])
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 834, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 865, in _recvMessage
    self._sendError(f, requestID)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 917, in _sendError
    self.sendCall("error", requestID, self.serialize(fail))
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 771, in serialize
    return jelly(object, self.security, None, self)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 892, in jelly
    return _Jellier(taster, persistentStore, invoker).jelly(object)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 417, in jelly
    return obj.jellyFor(self)
  File "/home/scmikes/python2.5/trunk/twisted/spread/flavors.py", line 308, in jellyFor
    sxp.extend([t, jellier.jelly(state)])
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 477, in jelly
    sxp.append([self.jelly(key), self.jelly(val)])
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 469, in jelly
    sxp.append(self.jelly(item))
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 505, in jelly
    (objType, obj))
<class 'twisted.spread.jelly.InsecureJelly'>: Type not allowed for object: <type 'type'> <class 'twisted.test.test_pbfailure.DieError'>
===============================================================================
[ERROR]: twisted.test.test_pbfailure.PBFailureTest.testPBFailures

Traceback (most recent call last):
Failure: <class 'twisted.internet.defer.FirstError'>: FirstError(<twisted.python.failure.Failure <class 'twisted.spread.pb.PBConnectionLost'>>, 0)
===============================================================================
[ERROR]: twisted.test.test_pbfailure.PBFailureTest.testPBFailures

Traceback (most recent call last):
Failure: <class 'twisted.test.test_pbfailure.PoopError'>: Someone threw poopie at me!
===============================================================================
[ERROR]: twisted.test.test_pbfailure.PBFailureTestUnsafe.testCopiedFailureLogging

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/internet/selectreactor.py", line 139, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/home/scmikes/python2.5/trunk/twisted/internet/tcp.py", line 348, in doRead
    return self.protocol.dataReceived(data)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 184, in dataReceived
    gotItem(item)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 114, in gotItem
    self.callExpressionReceived(item)
  File "/home/scmikes/python2.5/trunk/twisted/spread/banana.py", line 81, in callExpressionReceived
    self.expressionReceived(obj)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 523, in expressionReceived
    method(*sexp[1:])
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 834, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 865, in _recvMessage
    self._sendError(f, requestID)
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 917, in _sendError
    self.sendCall("error", requestID, self.serialize(fail))
  File "/home/scmikes/python2.5/trunk/twisted/spread/pb.py", line 771, in serialize
    return jelly(object, self.security, None, self)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 892, in jelly
    return _Jellier(taster, persistentStore, invoker).jelly(object)
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 417, in jelly
    return obj.jellyFor(self)
  File "/home/scmikes/python2.5/trunk/twisted/spread/flavors.py", line 308, in jellyFor
    sxp.extend([t, jellier.jelly(state)])
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 477, in jelly
    sxp.append([self.jelly(key), self.jelly(val)])
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 469, in jelly
    sxp.append(self.jelly(item))
  File "/home/scmikes/python2.5/trunk/twisted/spread/jelly.py", line 505, in jelly
    (objType, obj))
<class 'twisted.spread.jelly.InsecureJelly'>: Type not allowed for object: <type 'type'> <class 'twisted.test.test_pbfailure.DieError'>
===============================================================================
[ERROR]: twisted.test.test_pbfailure.PBFailureTestUnsafe.testPBFailures

Traceback (most recent call last):
Failure: <class 'twisted.internet.defer.FirstError'>: FirstError(<twisted.python.failure.Failure <class 'twisted.spread.pb.PBConnectionLost'>>, 0)
===============================================================================
[ERROR]: twisted.test.test_pbfailure.PBFailureTestUnsafe.testPBFailures

Traceback (most recent call last):
Failure: <class 'twisted.test.test_pbfailure.PoopError'>: Someone threw poopie at me!
===============================================================================
[ERROR]: twisted.test.test_udp.MulticastTestCase.testMulticast

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_udp.py", line 679, in testMulticast
    self.assertEquals(self.server.packets[0][0], "hello world")
<type 'exceptions.IndexError'>: list index out of range
===============================================================================
[ERROR]: twisted.test.test_zipstream.ZipstreamTest.test_unzipping

Traceback (most recent call last):
  File "/home/scmikes/python2.5/trunk/twisted/test/test_zipstream.py", line 44, in test_unzipping
    r=uziter.next()
  File "/home/scmikes/python2.5/trunk/twisted/python/zipstream.py", line 224, in unzipIterChunky
    fp=czf.readfile(entry)
  File "/home/scmikes/python2.5/trunk/twisted/python/zipstream.py", line 26, in readfile
    self.fp.seek(zinfo.file_offset, 0)
<type 'exceptions.AttributeError'>: 'ZipInfo' object has no attribute 'file_offset'
