Index: twisted/topfiles/4856.bugfix
===================================================================
--- twisted/topfiles/4856.bugfix	(revision 0)
+++ twisted/topfiles/4856.bugfix	(revision 0)
@@ -0,0 +1 @@
+twisted.internet.error now has an __all__ and twisted.words.protocols.jabber.xmlstream has had ConnectionLost removed from its __all__
Index: twisted/internet/error.py
===================================================================
--- twisted/internet/error.py	(revision 30808)
+++ twisted/internet/error.py	(working copy)
@@ -24,8 +24,12 @@
         s = '%s.' % s
         return s
 
+
+
 class CannotListenError(BindError):
-    """This gets raised by a call to startListening, when the object cannot start listening.
+    """
+    This gets raised by a call to startListening, when the object cannotstart
+    listening.
 
     @ivar interface: the interface I tried to listen on
     @ivar port: the port I tried to listen on
@@ -44,12 +48,14 @@
                                                  self.socketError)
 
 
+
 class MulticastJoinError(Exception):
     """
     An attempt to join a multicast group failed.
     """
 
 
+
 class MessageLengthError(Exception):
     """Message is too long to send"""
 
@@ -61,6 +67,7 @@
         return s
 
 
+
 class DNSLookupError(IOError):
     """DNS lookup failed"""
 
@@ -72,6 +79,7 @@
         return s
 
 
+
 class ConnectInProgressError(Exception):
     """A connect operation was started and isn't done yet."""
 
@@ -95,57 +103,76 @@
         return s
 
 
+
 class ConnectBindError(ConnectError):
     """Couldn't bind"""
 
 
+
 class UnknownHostError(ConnectError):
     """Hostname couldn't be looked up"""
 
 
+
 class NoRouteError(ConnectError):
     """No route to host"""
 
 
+
 class ConnectionRefusedError(ConnectError):
     """Connection was refused by other side"""
 
 
+
 class TCPTimedOutError(ConnectError):
     """TCP connection timed out"""
 
 
+
 class BadFileError(ConnectError):
     """File used for UNIX socket is no good"""
 
 
+
 class ServiceNameUnknownError(ConnectError):
     """Service name given as port is unknown"""
 
 
+
 class UserError(ConnectError):
     """User aborted connection"""
 
 
+
 class TimeoutError(UserError):
     """User timeout caused connection failure"""
 
+
+
 class SSLError(ConnectError):
     """An SSL error occurred"""
 
+
+
 class VerifyError(Exception):
     """Could not verify something that was supposed to be signed.
     """
 
+
+
 class PeerVerifyError(VerifyError):
     """The peer rejected our verify error.
     """
 
+
+
 class CertificateError(Exception):
     """
     We did not find a certificate where we expected to find one.
     """
 
+
+
 try:
     import errno
     errnoMapping = {
@@ -159,6 +186,8 @@
 except ImportError:
     errnoMapping = {}
 
+
+
 def getConnectError(e):
     """Given a socket exception, return connection error."""
     try:
@@ -205,10 +234,12 @@
         return s
 
 
+
 class ConnectionFdescWentAway(ConnectionLost):
     """Uh""" #TODO
 
 
+
 class AlreadyCalled(ValueError):
     """Tried to cancel an already-called event"""
 
@@ -220,6 +251,7 @@
         return s
 
 
+
 class AlreadyCancelled(ValueError):
     """Tried to cancel an already-cancelled event"""
 
@@ -265,6 +297,7 @@
         self.status = status
 
 
+
 class ProcessTerminated(ConnectionLost):
     """A process has ended with a probable error condition"""
 
@@ -278,6 +311,7 @@
         Exception.__init__(self, s)
 
 
+
 class ProcessExitedAlready(Exception):
     """
     The process has already exited and the operation requested can no longer
@@ -285,6 +319,7 @@
     """
 
 
+
 class NotConnectingError(RuntimeError):
     """The Connector was not connecting when it was asked to stop connecting"""
 
@@ -295,6 +330,8 @@
         s = '%s.' % s
         return s
 
+
+
 class NotListeningError(RuntimeError):
     """The Port was not listening when it was asked to stop listening"""
 
@@ -306,12 +343,14 @@
         return s
 
 
+
 class ReactorNotRunning(RuntimeError):
     """
     Error raised when trying to stop a reactor which is not running.
     """
 
 
+
 class ReactorAlreadyRunning(RuntimeError):
     """
     Error raised when trying to start the reactor multiple times.
@@ -341,3 +380,18 @@
         """
         Exception.__init__(self, address)
         self.address = address
+
+
+
+__all__ = ['BindError', 'CannotListenError', 'MulticastJoinError',
+        'MessageLengthError', 'DNSLookupError', 'ConnectInProgressError',
+        'ConnectError', 'ConnectBindError', 'UnknownHostError', 'NoRouteError',
+        'ConnectionRefusedError', 'TCPTimedOutError', 'BadFileError',
+        'ServiceNameUnknownError', 'UserError', 'TimeoutError', 'SSLError',
+        'VerifyError', 'PeerVerifyError', 'CertificateError',
+        'getConnectError', 'ConnectionClosed', 'ConnectionLost',
+        'ConnectionDone', 'ConnectionFdescWentAway', 'AlreadyCalled',
+        'AlreadyCancelled', 'PotentialZombieWarning', 'ProcessDone',
+        'ProcessTerminated', 'ProcessExitedAlready', 'NotConnectingError',
+        'NotListeningError', 'ReactorNotRunning', 'ReactorAlreadyRunning',
+        'ReactorAlreadyInstalledError', 'ConnectingCancelledError']
Index: twisted/words/protocols/jabber/xmlstream.py
===================================================================
--- twisted/words/protocols/jabber/xmlstream.py	(revision 30808)
+++ twisted/words/protocols/jabber/xmlstream.py	(working copy)
@@ -1125,7 +1125,7 @@
 
 
 __all__ = ['Authenticator', 'BaseFeatureInitiatingInitializer',
-           'ConnectAuthenticator', 'ConnectionLost', 'FeatureNotAdvertized',
+           'ConnectAuthenticator', 'FeatureNotAdvertized',
            'INIT_FAILED_EVENT', 'IQ', 'ListenAuthenticator', 'NS_STREAMS',
            'NS_XMPP_TLS', 'Reset', 'STREAM_AUTHD_EVENT',
            'STREAM_CONNECTED_EVENT', 'STREAM_END_EVENT', 'STREAM_ERROR_EVENT',
