Index: twisted/test/test_adbapi.py
===================================================================
--- twisted/test/test_adbapi.py	(revision 26733)
+++ twisted/test/test_adbapi.py	(working copy)
@@ -772,3 +772,22 @@
         d.addCallback(cbFailed)
         return d
 
+    def test_closeWithoutStartAttributeErrorFix(self):
+        """
+        close() should not raise an AttributeError when called without start()
+        being called first. See Trac Ticket #2680.
+        """
+        class _FakeDBDriver():
+            __all__ = []
+            apilevel = '2.0'
+            threadsafety = 1
+
+        import sys
+        sys.modules['FakeDBDriver'] = _FakeDBDriver()
+
+        pool = ConnectionPool('FakeDBDriver')
+        try:
+            pool.close()
+        except AttributeError:
+            self.fail("ConnectionPool.close() raised attribute error")
+            
Index: twisted/enterprise/adbapi.py
===================================================================
--- twisted/enterprise/adbapi.py	(revision 26733)
+++ twisted/enterprise/adbapi.py	(working copy)
@@ -216,6 +216,10 @@
         from twisted.internet import reactor
         self.startID = reactor.callWhenRunning(self._start)
 
+        # shutdownID is set in start(); set to None here so close() doesn't
+        # raise an exception if called without start() being called first.
+        self.shutdownID = None
+
     def _start(self):
         self.startID = None
         return self.start()
