cd src/pyfec && python ./setup.py  install --install-lib="c:\playground\allmydata\tahoe\instdir" --install-scripts="c:\playground\allmydata\tahoe\instdir/scripts"
/usr/lib/python2.5/distutils/dist.py:263: UserWarning: Unknown distribution option: 'summary'
  warnings.warn(msg)
/usr/lib/python2.5/distutils/dist.py:263: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing c:\playground\allmydata\tahoe\instdir/pyfec-0.99-py2.5.egg-info
Writing c:\playground\allmydata\tahoe\instdir/pyfec-0.99-py2.5.egg-info
cd src/Crypto && python ./setup.py  install --install-lib="c:\playground\allmydata\tahoe\instdir" --install-scripts="c:\playground\allmydata\tahoe\instdir/scripts"
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing c:\playground\allmydata\tahoe\instdir/pycrypto-2.0.1-py2.5.egg-info
Writing c:\playground\allmydata\tahoe\instdir/pycrypto-2.0.1-py2.5.egg-info
python setup.py  install --install-lib="c:\playground\allmydata\tahoe\instdir" --install-scripts="c:\playground\allmydata\tahoe\instdir/scripts"
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of c:\playground\allmydata\tahoe\instdir/scripts/allmydata-tahoe to 775
running install_egg_info
Removing c:\playground\allmydata\tahoe\instdir/AllMyData-0.0.1-py2.5.egg-info
Writing c:\playground\allmydata\tahoe\instdir/AllMyData-0.0.1-py2.5.egg-info
PYTHONPATH=/c/playground/cygwinreg/:/usr/local/lib/python2.5/site-packages:/cygdrive/c/playground/allmydata/tahoe/instdir python /usr/bin/trial --reactor=poll  allmydata.test.test_system.SystemTest
Running 3 tests.
allmydata.test.test_system
  SystemTest
    test_connections ...                                                [31;1m[ERROR][0m
[31;1m    cleanup errors[0m                                               [31;1m[ERROR][0m

/usr/lib/python2.5/site-packages/twisted/trial/reporter.py:219: twisted.trial.reporter.BrokenTestCaseWarning: REACTOR UNCLEAN! traceback(s) follow: 
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/trial/unittest.py", line 635, in _cleanUp
    util._Janitor().postCaseCleanup()
  File "/usr/lib/python2.5/site-packages/twisted/trial/util.py", line 64, in postCaseCleanup
    return self._dispatch('cleanPending')
  File "/usr/lib/python2.5/site-packages/twisted/trial/util.py", line 72, in _dispatch
    getattr(self, "do_%s" % attr)()
  File "/usr/lib/python2.5/site-packages/twisted/internet/utils.py", line 164, in warningSuppressingWrapper
    return runWithWarningsSuppressed(suppressedWarnings, f, *a, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/internet/utils.py", line 144, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/usr/lib/python2.5/site-packages/twisted/trial/util.py", line 91, in do_cleanPending
    raise PendingTimedCallsError(s)
twisted.trial.util.PendingTimedCallsError: pendingTimedCalls still pending (consider setting twisted.internet.base.DelayedCall.debug = True): <DelayedCall 2134251852 [0.0350000858307s] called=0 cancelled=0 Deferred.callback(None)>
 <DelayedCall 2134251180 [0.625s] called=0 cancelled=0 _resetLogDateTime()>


                                               [31;1m[ERROR][0m
                                               [31;1m[ERROR][0m
[31;1m    cleanup errors[0m                                               [31;1m[ERROR][0m

/usr/lib/python2.5/site-packages/twisted/trial/reporter.py:219: twisted.trial.reporter.BrokenTestCaseWarning: REACTOR UNCLEAN! traceback(s) follow: 
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/trial/unittest.py", line 652, in _classCleanUp
    util._Janitor().postClassCleanup()
  File "/usr/lib/python2.5/site-packages/twisted/trial/util.py", line 68, in postClassCleanup
    'cleanPending', 'cleanThreads')
  File "/usr/lib/python2.5/site-packages/twisted/trial/util.py", line 72, in _dispatch
    getattr(self, "do_%s" % attr)()
  File "/usr/lib/python2.5/site-packages/twisted/trial/util.py", line 126, in do_cleanReactor
    raise DirtyReactorError(' '.join(s))
twisted.trial.util.DirtyReactorError: THIS WILL BECOME AN ERROR SOON! reactor left in unclean state, the following Selectables were left over:  <<class 'twisted.internet.tcp.Port'> of foolscap.pb.Listener on 3287> <<class 'twisted.internet.tcp.Port'> of foolscap.pb.Listener on 3290> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3287) at 7f5796ec> <<class 'twisted.internet.tcp.Port'> of nevow.appserver.NevowSite on 3291> <<class 'twisted.internet.tcp.Port'> of foolscap.pb.Listener on 3292> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3292) at 7f665cec> <<class 'twisted.internet.tcp.Port'> of foolscap.pb.Listener on 3293> <<class 'twisted.internet.tcp.TLSConnection'> to ('127.0.0.1', 3287) at 7f61f60c> <Negotiation #10 on 0> <Negotiation #2 on 0> <<class 'twisted.internet.tcp.Port'> of foolscap.pb.Listener on 3294> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3293) at 7f665fcc> <Negotiation #4 on 0> <<class 'twisted.internet.tcp.Port'> of foolscap.pb.Listener on 3295> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3294) at 7f67030c> <Negotiation #12 on 0> <Negotiation #6 on 0> <<class 'twisted.internet.tcp.TLSConnection'> to ('127.0.0.1', 3287) at 7f842aac> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3294) at 7f67686c> <<class 'twisted.internet.tcp.TLSConnection'> to ('127.0.0.1', 3287) at 7f8491cc> <<class 'twisted.internet.tcp.TLSConnection'> to ('127.0.0.1', 3287) at 7f8498cc> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3294) at 7f68144c> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3295) at 7f68f6cc> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3295) at 7f68fc4c> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3295) at 7f6051cc> <<class 'twisted.internet.tcp.TLSConnection'> to ('192.168.180.128', 3295) at 7f61068c> <Negotiation #0 on 0> <Negotiation #0 on 0> <Negotiation #0 on 0> <Negotiation #2 on 0> <Negotiation #5 on 0> <Negotiation #0 on 0> <Negotiation #2 on 0> <Negotiation #5 on 0> <Negotiation #7 on 0>

    test_upload_and_download ...                                        [31;1m[ERROR][0m
    test_vdrive ...                                                     [31;1m[ERROR][0m

===============================================================================
[ERROR]: allmydata.test.test_system.SystemTest.test_connections

Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <allmydata.test.test_system.SystemTest testMethod=test_connections> (test_connections) still running at 120.0 secs
===============================================================================
[ERROR]: allmydata.test.test_system.SystemTest.test_connections

Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.
===============================================================================
[ERROR]: allmydata.test.test_system.SystemTest.test_connections

Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.
===============================================================================
[ERROR]: allmydata.test.test_system.SystemTest.test_upload_and_download

Traceback (most recent call last):
  File "c:\playground\allmydata\tahoe\instdir/allmydata/test/test_system.py", line 123, in test_upload_and_download
    d = self.set_up_nodes()
  File "c:\playground\allmydata\tahoe\instdir/allmydata/test/test_system.py", line 44, in set_up_nodes
    self.queen = self.add_service(queen.Queen(basedir="queen"))
  File "c:\playground\allmydata\tahoe\instdir/allmydata/test/test_system.py", line 37, in add_service
    s.setServiceParent(self.sparent)
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 148, in setServiceParent
    self.parent.addService(self)
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 259, in addService
    service.privilegedStartService()
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 228, in privilegedStartService
    service.privilegedStartService()
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 228, in privilegedStartService
    service.privilegedStartService()
  File "/usr/lib/python2.5/site-packages/twisted/application/internet.py", line 68, in privilegedStartService
    self._port = self._getPort()
  File "/usr/lib/python2.5/site-packages/twisted/application/internet.py", line 86, in _getPort
    return getattr(reactor, 'listen'+self.method)(*self.args, **self.kwargs)
  File "/usr/lib/python2.5/site-packages/twisted/internet/posixbase.py", line 467, in listenTCP
    p.startListening()
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 733, in startListening
    raise CannotListenError, (self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:3287: (112, 'Address already in use').
===============================================================================
[ERROR]: allmydata.test.test_system.SystemTest.test_vdrive

Traceback (most recent call last):
  File "c:\playground\allmydata\tahoe\instdir/allmydata/test/test_system.py", line 144, in test_vdrive
    d = self.set_up_nodes()
  File "c:\playground\allmydata\tahoe\instdir/allmydata/test/test_system.py", line 44, in set_up_nodes
    self.queen = self.add_service(queen.Queen(basedir="queen"))
  File "c:\playground\allmydata\tahoe\instdir/allmydata/test/test_system.py", line 37, in add_service
    s.setServiceParent(self.sparent)
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 148, in setServiceParent
    self.parent.addService(self)
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 259, in addService
    service.privilegedStartService()
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 228, in privilegedStartService
    service.privilegedStartService()
  File "/usr/lib/python2.5/site-packages/twisted/application/service.py", line 228, in privilegedStartService
    service.privilegedStartService()
  File "/usr/lib/python2.5/site-packages/twisted/application/internet.py", line 68, in privilegedStartService
    self._port = self._getPort()
  File "/usr/lib/python2.5/site-packages/twisted/application/internet.py", line 86, in _getPort
    return getattr(reactor, 'listen'+self.method)(*self.args, **self.kwargs)
  File "/usr/lib/python2.5/site-packages/twisted/internet/posixbase.py", line 467, in listenTCP
    p.startListening()
  File "/usr/lib/python2.5/site-packages/twisted/internet/tcp.py", line 733, in startListening
    raise CannotListenError, (self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:3287: (112, 'Address already in use').
-------------------------------------------------------------------------------
Ran 3 tests in 121.078s

FAILED (errors=5)
make: *** [test] Error 1
